name: build

on:
  schedule:
    - cron: "0 12 * * 6"  # 8 PM CST every Saturday
  push:
    branches:
      - pac
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build
      env:
        PROXY: ${{ secrets.PROXY }}
      run: |
        cd pac && python3 build.py
        cp ./pac/dist/pac-gfwlist-17mon.txt ./pac/dist/pac
        sed -i "s/__PROXY__/$PROXY/g" ./pac/dist/pac

    - name: deploy file to server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
          username: ${{ secrets.FTP_USERNAME }}
          server: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: './pac/dist/'